services:
  - type: web
    name: case-management-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd api && uvicorn index:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0 